version: "3.7"
services:

  friendsternet:
    build: .
    ports:
      - "8080:8080"
    networks:
      - backend
    command: "mvn spring-boot:run"
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure

networks:
  backend:
